FROM centos:latest
RUN yum update -y
RUN yum install epel-release -y
RUN yum update -y
RUN yum install python-pip -y
RUN pip install --upgrade pip
RUN pip install awscli
RUN yum install dcfldd -y
RUN curl -O http://poc5.stratoscale.com/install-client.sh
RUN bash ./install-client.sh http://poc5.stratoscale.com
RUN export SYMP_URL="http://poc5.stratoscale.com"
RUN yum install s3cmd -y
Run yum install nano -y
RUN yum install openssh-clients -y
RUN yum install openvpn -y
CMD /bin/bash

